// apps/nuxt-example/components/WalletSelector/WalletSelector.vue
<script setup lang="ts">
import {
  AdapterWallet,
  CEDRA_CONNECT_ACCOUNT_URL,
  isCedraConnectWallet,
  truncateAddress,
} from "@cedra-labs/wallet-adapter-vue";
import { Copy, LogOut, User } from "lucide-vue-next";
import { DialogRoot as Dialog, DialogTrigger } from "radix-vue";

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";
import { useToast } from "~/components/ui/toast";
import { useNuxtApp } from "#app";
const { $walletAdapter } = useNuxtApp();
const { account, connected, disconnect, wallet, wallets, connect } =
  $walletAdapter || {};

const { toast } = useToast();
const isDialogOpen = ref(false);

function closeDialog() {
  isDialogOpen.value = false;
}

async function copyAddress() {
  if (!account?.value?.address) return;
  try {
    await navigator.clipboard.writeText(account.value.address.toString());
    toast({
      title: "Success",
      description: "Copied wallet address to clipboard.",
    });
  } catch {
    toast({
      variant: "destructive",
      title: "Error",
      description: "Failed to copy wallet address.",
    });
  }
}

async function connectWallet(wallet: AdapterWallet) {
  await connect(wallet.name);
}
</script>

<template>
  <template v-if="connected">
    <DropdownMenu>
      <DropdownMenuTrigger as-child>
        <Button>
          {{
            account?.ansName ||
            truncateAddress(account?.address?.toString() || "") ||
            "Unknown"
          }}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem @click="copyAddress" class="gap-2">
          <Copy class="h-4 w-4" /> Copy Address
        </DropdownMenuItem>
        <template v-if="wallet && isCedraConnectWallet(wallet)">
          <DropdownMenuItem as-child>
            <a
              :href="CEDRA_CONNECT_ACCOUNT_URL"
              target="_blank"
              rel="noopener noreferrer"
              class="flex items-center gap-2"
            >
              <User class="h-4 w-4" /> Account
            </a>
          </DropdownMenuItem>
        </template>
        <DropdownMenuItem @click="disconnect" class="gap-2">
          <LogOut class="h-4 w-4" /> Disconnect
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  </template>
  <template v-else>
    <Dialog class="w-96">
      <DialogTrigger asChild>
        <Button>Connect Wallet</Button>
      </DialogTrigger>
      <ConnectWalletDialog
        v-if="wallets && Array.isArray(wallets)"
        @close="closeDialog"
        @connect="connectWallet"
        :wallets="wallets"
      />
    </Dialog>
  </template>
</template>

// apps/nextjs-x-chain/src/components/WalletSelector.tsx
"use client";

import {
  CEDRA_CONNECT_ACCOUNT_URL,
  AboutCedraConnect,
  AboutCedraConnectEducationScreen,
  AdapterNotDetectedWallet,
  AdapterWallet,
  CedraPrivacyPolicy,
  WalletItem,
  WalletSortingOptions,
  groupAndSortWallets,
  isCedraConnectWallet,
  isInstallRequired,
  truncateAddress,
  useWallet,
} from "@cedra-labs/wallet-adapter-react";
import {
  ArrowLeft,
  ArrowRight,
  ChevronDown,
  Copy,
  LogOut,
  User,
} from "lucide-react";
import { useCallback, useState } from "react";
import { Button } from "./ui/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "./ui/collapsible";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "./ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";
import { useToast } from "./ui/use-toast";
import { Tabs, TabsList, TabsTrigger } from "./ui/tabs";
import { TabsContent } from "./ui/tabs";

export function WalletSelector(walletSortingOptions: WalletSortingOptions) {
  const { account, connected, disconnect, wallet } = useWallet();
  const { toast } = useToast();
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  const closeDialog = useCallback(() => setIsDialogOpen(false), []);

  const copyAddress = useCallback(async () => {
    if (!account?.address) return;
    try {
      await navigator.clipboard.writeText(account.address.toString());
      toast({
        title: "Success",
        description: "Copied wallet address to clipboard.",
      });
    } catch {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to copy wallet address.",
      });
    }
  }, [account?.address, toast]);

  return connected ? (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button>
          {account?.ansName ||
            truncateAddress(account?.address?.toString()) ||
            "Unknown"}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onSelect={copyAddress} className="gap-2">
          <Copy className="h-4 w-4" /> Copy address
        </DropdownMenuItem>
        {wallet && isCedraConnectWallet(wallet) && (
          <DropdownMenuItem asChild>
            <a
              href={CEDRA_CONNECT_ACCOUNT_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="flex gap-2"
            >
              <User className="h-4 w-4" /> Account
            </a>
          </DropdownMenuItem>
        )}
        <DropdownMenuItem onSelect={disconnect} className="gap-2">
          <LogOut className="h-4 w-4" /> Disconnect
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  ) : (
    <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
      <DialogTrigger asChild>
        <Button>Connect a Wallet</Button>
      </DialogTrigger>
      <ConnectWalletDialog close={closeDialog} {...walletSortingOptions} />
    </Dialog>
  );
}

interface ConnectWalletDialogProps extends WalletSortingOptions {
  close: () => void;
}

function ConnectWalletDialog({
  close,
  ...walletSortingOptions
}: ConnectWalletDialogProps) {
  const { wallets = [], notDetectedWallets = [] } = useWallet();

  const { cedraConnectWallets, availableWallets, installableWallets } =
    groupAndSortWallets(
      [...wallets, ...notDetectedWallets],
      walletSortingOptions
    );

  const hasCedraConnectWallets = !!cedraConnectWallets.length;

  const { evmWallets, solanaWallets, cedraWallets } = availableWallets.reduce<{
    evmWallets: AdapterWallet[];
    solanaWallets: AdapterWallet[];
    cedraWallets: AdapterWallet[];
  }>(
    (acc, wallet) => {
      if (wallet.name.includes("Ethereum")) {
        acc.evmWallets.push(wallet);
      } else if (wallet.name.includes("Solana")) {
        acc.solanaWallets.push(wallet);
      } else {
        acc.cedraWallets.push(wallet);
      }
      return acc;
    },
    { evmWallets: [], solanaWallets: [], cedraWallets: [] }
  );

  return (
    <DialogContent className="max-h-screen overflow-auto">
      <AboutCedraConnect renderEducationScreen={renderEducationScreen}>
        <DialogHeader>
          <DialogTitle className="flex flex-col text-center leading-snug">
            {hasCedraConnectWallets ? (
              <>
                <span>Log in or sign up</span>
                <span>with Social + Cedra Connect</span>
              </>
            ) : (
              "Connect Wallet"
            )}
          </DialogTitle>
        </DialogHeader>

        {hasCedraConnectWallets && (
          <div className="flex flex-col gap-2 pt-3">
            {cedraConnectWallets.map((wallet) => (
              <CedraConnectWalletRow
                key={wallet.name}
                wallet={wallet}
                onConnect={close}
              />
            ))}
            <p className="flex gap-1 justify-center items-center text-muted-foreground text-sm">
              Learn more about{" "}
              <AboutCedraConnect.Trigger className="flex gap-1 py-3 items-center text-foreground">
                Cedra Connect <ArrowRight size={16} />
              </AboutCedraConnect.Trigger>
            </p>
            <CedraPrivacyPolicy className="flex flex-col items-center py-1">
              <p className="text-xs leading-5">
                <CedraPrivacyPolicy.Disclaimer />{" "}
                <CedraPrivacyPolicy.Link className="text-muted-foreground underline underline-offset-4" />
                <span className="text-muted-foreground">.</span>
              </p>
              <CedraPrivacyPolicy.PoweredBy className="flex gap-1.5 items-center text-xs leading-5 text-muted-foreground" />
            </CedraPrivacyPolicy>
            <div className="flex items-center gap-3 pt-4 text-muted-foreground">
              <div className="h-px w-full bg-secondary" />
              Or
              <div className="h-px w-full bg-secondary" />
            </div>
          </div>
        )}

        <div className="flex flex-col gap-3 pt-3">
          {/* Handle Cedra wallets */}
          <Tabs defaultValue="cedra">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="cedra">Cedra</TabsTrigger>
              <TabsTrigger value="solana">Solana</TabsTrigger>
              <TabsTrigger value="ethereum">Ethereum</TabsTrigger>
            </TabsList>
            <TabsContent value="cedra">
              {cedraWallets.map((wallet) => (
                <WalletRow
                  key={wallet.name}
                  wallet={wallet}
                  onConnect={close}
                />
              ))}
              {!!installableWallets.length && (
                <Collapsible className="flex flex-col gap-3 pt-3">
                  <CollapsibleTrigger asChild>
                    <Button size="sm" variant="ghost" className="gap-2">
                      More wallets <ChevronDown />
                    </Button>
                  </CollapsibleTrigger>
                  <CollapsibleContent className="flex flex-col gap-3">
                    {installableWallets.map((wallet) => (
                      <WalletRow
                        key={wallet.name}
                        wallet={wallet}
                        onConnect={close}
                      />
                    ))}
                  </CollapsibleContent>
                </Collapsible>
              )}
            </TabsContent>
            {/* Handle Solana wallets */}
            <TabsContent value="solana">
              {solanaWallets.map((wallet) => (
                <WalletRow
                  key={wallet.name}
                  wallet={wallet}
                  onConnect={close}
                />
              ))}
            </TabsContent>
            {/* Handle Ethereum wallets */}
            <TabsContent value="ethereum">
              {evmWallets.map((wallet) => (
                <WalletRow
                  key={wallet.name}
                  wallet={wallet}
                  onConnect={close}
                />
              ))}
            </TabsContent>
          </Tabs>
        </div>
      </AboutCedraConnect>
    </DialogContent>
  );
}

interface WalletRowProps {
  wallet: AdapterWallet | AdapterNotDetectedWallet;
  onConnect?: () => void;
}

function WalletRow({ wallet, onConnect }: WalletRowProps) {
  return (
    <WalletItem
      wallet={wallet}
      onConnect={onConnect}
      className="flex items-center justify-between px-4 py-3 gap-4 border rounded-md"
    >
      <div className="flex items-center gap-4">
        <WalletItem.Icon className="h-6 w-6" />
        <WalletItem.Name className="text-base font-normal" />
      </div>
      {isInstallRequired(wallet) ? (
        <Button size="sm" variant="ghost" asChild>
          <WalletItem.InstallLink />
        </Button>
      ) : (
        <WalletItem.ConnectButton asChild>
          <Button size="sm">Connect</Button>
        </WalletItem.ConnectButton>
      )}
    </WalletItem>
  );
}

function CedraConnectWalletRow({ wallet, onConnect }: WalletRowProps) {
  return (
    <WalletItem wallet={wallet} onConnect={onConnect}>
      <WalletItem.ConnectButton asChild>
        <Button size="lg" variant="outline" className="w-full gap-4">
          <WalletItem.Icon className="h-5 w-5" />
          <WalletItem.Name className="text-base font-normal" />
        </Button>
      </WalletItem.ConnectButton>
    </WalletItem>
  );
}

function renderEducationScreen(screen: AboutCedraConnectEducationScreen) {
  return (
    <>
      <DialogHeader className="grid grid-cols-[1fr_4fr_1fr] items-center space-y-0">
        <Button variant="ghost" size="icon" onClick={screen.cancel}>
          <ArrowLeft />
        </Button>
        <DialogTitle className="leading-snug text-base text-center">
          About Cedra Connect
        </DialogTitle>
      </DialogHeader>

      <div className="flex h-[162px] pb-3 items-end justify-center">
        <screen.Graphic />
      </div>
      <div className="flex flex-col gap-2 text-center pb-4">
        <screen.Title className="text-xl" />
        <screen.Description className="text-sm text-muted-foreground [&>a]:underline [&>a]:underline-offset-4 [&>a]:text-foreground" />
      </div>

      <div className="grid grid-cols-3 items-center">
        <Button
          size="sm"
          variant="ghost"
          onClick={screen.back}
          className="justify-self-start"
        >
          Back
        </Button>
        <div className="flex items-center gap-2 place-self-center">
          {screen.screenIndicators.map((ScreenIndicator, i) => (
            <ScreenIndicator key={i} className="py-4">
              <div className="h-0.5 w-6 transition-colors bg-muted [[data-active]>&]:bg-foreground" />
            </ScreenIndicator>
          ))}
        </div>
        <Button
          size="sm"
          variant="ghost"
          onClick={screen.next}
          className="gap-2 justify-self-end"
        >
          {screen.screenIndex === screen.totalScreens - 1 ? "Finish" : "Next"}
          <ArrowRight size={16} />
        </Button>
      </div>
    </>
  );
}
