// apps/nextjs-example/src/components/transactionFlows/SingleSigner.tsx
import { isSendableNetwork, cedraClient } from "@/utils";
import { parseTypeTag, AccountAddress, U64 } from "@cedra-labs/ts-sdk";
import { InputTransactionData } from "@cedra-labs/wallet-adapter-core";
import { useWallet } from "@cedra-labs/wallet-adapter-react";
import { Button } from "../ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "../ui/card";
import { useToast } from "../ui/use-toast";
import { TransactionHash } from "../TransactionHash";

const CEDRA_COIN = "0x1::cedra_coin::CedraCoin";

/**
 * Generate a nonce with alphanumeric characters only.
 * This is a requirement for Sign in With Solana nonces
 */
function generateNonce() {
  return crypto.randomUUID().replaceAll("-", "");
}

export function SingleSigner() {
  const { toast } = useToast();
  const {
    connected,
    account,
    network,
    signAndSubmitTransaction,
    signMessageAndVerify,
    signMessage,
    signTransaction,
  } = useWallet();
  let sendable = isSendableNetwork(connected, network?.name);

  const onSignMessageAndVerify = async () => {
    const payload = {
      message: "Hello from Cedra Wallet Adapter",
      nonce: generateNonce(),
    };
    const response = await signMessageAndVerify(payload);
    toast({
      title: "Success",
      description: JSON.stringify({ onSignMessageAndVerify: response }),
    });
  };

  const onSignMessage = async () => {
    const payload = {
      message: "Hello from Cedra Wallet Adapter",
      nonce: generateNonce(),
    };
    const response = await signMessage(payload);
    toast({
      title: "Success",
      description: JSON.stringify({ onSignMessage: response }),
    });
  };

  const onSignAndSubmitTransaction = async () => {
    if (!account) return;
    const transaction: InputTransactionData = {
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [CEDRA_COIN],
        functionArguments: [account.address, 1], // 1 is in Octas
      },
    };
    try {
      const response = await signAndSubmitTransaction(transaction);
      await cedraClient(network).waitForTransaction({
        transactionHash: response.hash,
      });
      toast({
        title: "Success",
        description: <TransactionHash hash={response.hash} network={network} />,
      });
    } catch (error) {
      console.error(error);
    }
  };

  const onSignAndSubmitScriptTransaction = async () => {
    if (!account) return;
    const transaction: InputTransactionData = {
      data: {
        bytecode:
          "0xa11ceb0b0700000a06010002030206050806070e2508334010731f010200030001000103060c050300083c53454c463e5f30046d61696e0d6170746f735f6163636f756e74087472616e73666572ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000114636f6d70696c6174696f6e5f6d65746164617461090003322e3003322e31000001050b000b010b02110002",
        typeArguments: [],
        functionArguments: [account.address, new U64(1)], // 1 is in Octas
      },
    };
    try {
      const response = await signAndSubmitTransaction(transaction);
      await cedraClient(network).waitForTransaction({
        transactionHash: response.hash,
      });
      toast({
        title: "Success",
        description: <TransactionHash hash={response.hash} network={network} />,
      });
    } catch (error) {
      console.error(error);
    }
  };

  const onSignAndSubmitBCSTransaction = async () => {
    if (!account) return;

    try {
      const response = await signAndSubmitTransaction({
        data: {
          function: "0x1::coin::transfer",
          typeArguments: [parseTypeTag(CEDRA_COIN)],
          functionArguments: [AccountAddress.from(account.address), new U64(1)], // 1 is in Octas
        },
      });
      await cedraClient(network).waitForTransaction({
        transactionHash: response.hash,
      });
      toast({
        title: "Success",
        description: <TransactionHash hash={response.hash} network={network} />,
      });
    } catch (error) {
      console.error(error);
    }
  };

  // Legacy typescript sdk support
  const onSignTransaction = async () => {
    try {
      const payload: InputTransactionData = {
        data: {
          function: "0x1::coin::transfer",
          typeArguments: [CEDRA_COIN],
          functionArguments: [account?.address.toString(), 1],
        },
      };
      const response = await signTransaction({
        transactionOrPayload: payload,
      });
      toast({
        title: "Success",
        description: JSON.stringify(response),
      });
    } catch (error) {
      console.error(error);
    }
  };

  const onSignRawTransaction = async () => {
    if (!account) return;

    try {
      const transactionToSign = await cedraClient(
        network,
      ).transaction.build.simple({
        sender: account.address,
        data: {
          function: "0x1::coin::transfer",
          typeArguments: [CEDRA_COIN],
          functionArguments: [account.address.toString(), 1],
        },
      });
      const response = await signTransaction({
        transactionOrPayload: transactionToSign,
      });
      toast({
        title: "Success",
        description: JSON.stringify(response),
      });
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Single Signer Flow</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-wrap gap-4">
        <Button onClick={onSignAndSubmitTransaction} disabled={!sendable}>
          Sign and submit transaction
        </Button>
        <Button onClick={onSignAndSubmitScriptTransaction} disabled={!sendable}>
          Sign and submit script transaction
        </Button>
        <Button onClick={onSignAndSubmitBCSTransaction} disabled={!sendable}>
          Sign and submit BCS transaction
        </Button>
        <Button onClick={onSignTransaction} disabled={!sendable}>
          Sign transaction
        </Button>
        <Button onClick={onSignRawTransaction} disabled={!sendable}>
          Sign raw transaction
        </Button>
        <Button onClick={onSignMessage} disabled={!sendable}>
          Sign message
        </Button>
        <Button onClick={onSignMessageAndVerify} disabled={!sendable}>
          Sign message and verify
        </Button>
      </CardContent>
    </Card>
  );
}

// apps/nuxt-example/components/TransactonFlows/SingleSigner.vue
<script setup lang="ts">
import { computed, h } from "vue";
import { cedraClient, isSendableNetwork } from "@/utils";
import { AccountAddress, parseTypeTag, U64 } from "@cedra-labs/ts-sdk";
import { InputTransactionData } from "@cedra-labs/wallet-adapter-core";
import TransactionHash from "~/components/TransactionHash.vue";
import { useToast } from "~/components/ui/toast";
const { toast } = useToast();
const { $walletAdapter } = useNuxtApp();
const {
  network,
  connected,
  account,
  signAndSubmitTransaction,
  signMessageAndVerify,
  signMessage,
  signTransaction,
} = $walletAdapter;

const CEDRA_COIN = "0x1::cedra_coin::CedraCoin";

const isSendable = computed(() =>
  isSendableNetwork(connected.value, network.value?.name || undefined),
);

const onSignMessageAndVerify = async () => {
  const payload = {
    message: "Hello from Cedra Wallet Adapter",
    nonce: Math.random().toString(16),
  };
  const response = await signMessageAndVerify(payload);
  toast({
    title: "Success",
    description: JSON.stringify({ onSignMessageAndVerify: response }),
  });
};

const onSignMessage = async () => {
  const payload = {
    message: "Hello from Cedra Wallet Adapter",
    nonce: Math.random().toString(16),
  };
  const response = await signMessage(payload);
  toast({
    title: "Success",
    description: JSON.stringify({ onSignMessage: response }),
  });
};

const onSignAndSubmitTransaction = async () => {
  if (!account) return;
  const transaction: InputTransactionData = {
    data: {
      function: "0x1::coin::transfer",
      typeArguments: [CEDRA_COIN],
      functionArguments: [account.value?.address, 1], // 1 is in Octas
    },
  };
  try {
    const response = await signAndSubmitTransaction(transaction);
    await cedraClient(network.value).waitForTransaction({
      transactionHash: response.hash,
    });
    toast({
      title: "Success",
      description: h(TransactionHash, {
        hash: response.hash,
        network: network.value,
      }),
    });
  } catch (error) {
    console.error(error);
  }
};

const onSignAndSubmitBCSTransaction = async () => {
  if (!account.value) return;

  try {
    const response = await signAndSubmitTransaction({
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [parseTypeTag(CEDRA_COIN)],
        functionArguments: [
          AccountAddress.from(account.value?.address),
          new U64(1),
        ], // 1 is in Octas
      },
    });
    await cedraClient(network.value).waitForTransaction({
      transactionHash: response.hash,
    });
    toast({
      title: "Success",
      description: h(TransactionHash, {
        hash: response.hash,
        network: network.value,
      }),
    });
  } catch (error) {
    console.error(error);
  }
};

// Legacy typescript sdk support
const onSignTransaction = async () => {
  try {
    const payload = {
      type: "entry_function_payload",
      function: "0x1::coin::transfer",
      type_arguments: ["0x1::cedra_coin::CedraCoin"],
      arguments: [account.value?.address, 1], // 1 is in Octas
    };
    const response = await signTransaction(payload);
    toast({
      title: "Success",
      description: JSON.stringify(response),
    });
  } catch (error) {
    console.error(error);
  }
};

const onSignTransactionV2 = async () => {
  if (!account.value) return;

  try {
    const transactionToSign = await cedraClient(
      network.value,
    ).transaction.build.simple({
      sender: account.value?.address,
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [CEDRA_COIN],
        functionArguments: [account.value?.address, 1], // 1 is in Octas
      },
    });
    const response = await signTransaction(transactionToSign);
    toast({
      title: "Success",
      description: JSON.stringify(response),
    });
  } catch (error) {
    console.error(error);
  }
};
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Single Signer Flow</CardTitle>
    </CardHeader>
    <CardContent class="flex flex-wrap gap-4">
      <Button @click="onSignAndSubmitTransaction" :disabled="!isSendable">
        Sign and submit transaction
      </Button>
      <Button @click="onSignAndSubmitBCSTransaction" :disabled="!isSendable">
        Sign and submit BCS transaction
      </Button>
      <Button @click="onSignTransaction" :disabled="!isSendable">
        Sign transaction
      </Button>
      <Button @click="onSignTransactionV2" :disabled="!isSendable">
        Sign transaction V2
      </Button>
      <Button @click="onSignMessage" :disabled="!isSendable">
        Sign message
      </Button>
      <Button @click="onSignMessageAndVerify" :disabled="!isSendable">
        Sign message and verify
      </Button>
    </CardContent>
  </Card>
</template>
