// apps/nextjs-example/src/components/transactionFlows/Sponsor.tsx
import { cedraClient, isSendableNetwork } from "@/utils";
import {
  Account,
  AccountAddress,
  AccountAuthenticator,
  AnyRawTransaction,
} from "@cedra-labs/ts-sdk";
import { useWallet } from "@cedra-labs/wallet-adapter-react";
import { useState } from "react";
import { TransactionHash } from "../TransactionHash";
import { Button } from "../ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { useToast } from "../ui/use-toast";

export function Sponsor() {
  const { toast } = useToast();
  const { connected, account, network, signTransaction, submitTransaction } =
    useWallet();
  const [transactionToSubmit, setTransactionToSubmit] =
    useState<AnyRawTransaction | null>(null);

  const [senderAuthenticator, setSenderAuthenticator] =
    useState<AccountAuthenticator>();
  const [feepayerAuthenticator, setFeepayerAuthenticator] =
    useState<AccountAuthenticator>();

  const [senderAccount, setSenderAccount] = useState<Account | null>();

  let sendable = isSendableNetwork(connected, network?.name);

  // Generate a raw transaction using the SDK
  const generateTransaction = async (
    sender: Account,
  ): Promise<AnyRawTransaction> => {
    if (!account) {
      throw new Error("no account");
    }
    const transactionToSign = await cedraClient(
      network,
    ).transaction.build.simple({
      sender: sender.accountAddress,
      withFeePayer: true,
      data: {
        function: "0x1::resource_account::create_resource_account",
        typeArguments: [],
        functionArguments: [
          account.address.toString(),
          AccountAddress.from("0x0").toUint8Array(),
        ],
      },
    });
    transactionToSign.feePayerAddress = account.address;
    return transactionToSign;
  };

  const onSignTransaction = async () => {
    let sender = Account.generate();
    setSenderAccount(sender);

    const transaction = await generateTransaction(sender);
    setTransactionToSubmit(transaction);

    try {
      const authenticator = cedraClient(network).transaction.sign({
        signer: sender,
        transaction: transaction,
      });
      setSenderAuthenticator(authenticator);
    } catch (error) {
      console.error(error);
    }
  };

  const onSignTransactionAsSponsor = async () => {
    if (!transactionToSubmit) {
      throw new Error("No Transaction to sign");
    }
    try {
      const response = await signTransaction({
        transactionOrPayload: transactionToSubmit,
        asFeePayer: true,
      });
      setFeepayerAuthenticator(response.authenticator);
    } catch (error) {
      console.error(error);
    }
  };

  const onSubmitTransaction = async () => {
    if (!transactionToSubmit) {
      throw new Error("No Transaction to sign");
    }
    if (!senderAuthenticator) {
      throw new Error("No senderAuthenticator");
    }
    if (!feepayerAuthenticator) {
      throw new Error("No feepayerAuthenticator");
    }
    try {
      const response = await submitTransaction({
        transaction: transactionToSubmit,
        senderAuthenticator: senderAuthenticator,
        feePayerAuthenticator: feepayerAuthenticator,
      });
      toast({
        title: "Success",
        description: <TransactionHash hash={response.hash} network={network} />,
      });
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Sponsor Transaction Flow</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-wrap gap-4">
        <Button onClick={onSignTransaction} disabled={!sendable}>
          Sign as sender
        </Button>
        <Button
          onClick={onSignTransactionAsSponsor}
          disabled={!sendable || !senderAuthenticator}
        >
          Sign as sponsor
        </Button>
        <Button
          onClick={onSubmitTransaction}
          disabled={!sendable || !senderAuthenticator}
        >
          Submit transaction
        </Button>
      </CardContent>
    </Card>
  );
}

// apps/nuxt-example/components/TransactonFlows/Sponsor.vue
<script setup lang="ts">
import { ref, computed, h } from "vue";
import { cedraClient, isSendableNetwork } from "@/utils";
import {
  AccountAuthenticator,
  AnyRawTransaction,
  Account,
} from "@cedra-labs/ts-sdk";
import TransactionHash from "~/components/TransactionHash.vue";
import { useToast } from "~/components/ui/toast";
const { toast } = useToast();
const { $walletAdapter } = useNuxtApp();
const { network, connected, account, signTransaction, submitTransaction } =
  $walletAdapter || {};

const CEDRA_COIN = "0x1::cedra_coin::CedraCoin";

const transactionToSubmit = ref<AnyRawTransaction>();
const senderAuthenticator = ref<AccountAuthenticator>();
const feepayerAuthenticator = ref<AccountAuthenticator>();

const isSendable = computed(() =>
  isSendableNetwork(connected.value, network.value?.name || undefined),
);

  // create sponsor account
  const SPONSOR_INITIAL_BALANCE = 100_000_000;
  const sponsor = Account.generate();

// Generate a raw transaction using the SDK
const generateTransaction = async (): Promise<AnyRawTransaction> => {
  if (!account.value) {
    throw new Error("no account");
  }
  const transactionToSign = await cedraClient(
    network.value,
  ).transaction.build.simple({
    sender: account.value?.address,
    withFeePayer: true,
    data: {
      function: "0x1::coin::transfer",
      typeArguments: [CEDRA_COIN],
      functionArguments: [account.value?.address, 1], // 1 is in Octas
    },
  });
  return transactionToSign;
};

const onSignTransaction = async () => {
  const transaction = await generateTransaction();
  transactionToSubmit.value = transaction;

  try {
    senderAuthenticator.value = await signTransaction(transaction);
  } catch (error) {
    console.error(error);
  }
};

const onSignTransactionAsSponsor = async () => {
  if (!transactionToSubmit.value) {
    throw new Error("No Transaction to sign");
  }
  try {
    await cedraClient(network.value).fundAccount({
        accountAddress: sponsor.accountAddress,
        amount: SPONSOR_INITIAL_BALANCE,
      });
    feepayerAuthenticator.value = await cedraClient(
        network.value
      ).transaction.signAsFeePayer({
        signer: sponsor,
        transaction: transactionToSubmit.value,
      });
  } catch (error) {
    console.error(error);
  }
};

const onSubmitTransaction = async () => {
  if (!transactionToSubmit.value) {
    throw new Error("No Transaction to sign");
  }
  if (!senderAuthenticator.value) {
    throw new Error("No senderAuthenticator");
  }
  if (!feepayerAuthenticator.value) {
    throw new Error("No feepayerAuthenticator");
  }
  try {
    const response = await submitTransaction({
      transaction: transactionToSubmit.value,
      senderAuthenticator: senderAuthenticator.value,
      feePayerAuthenticator: feepayerAuthenticator.value,
    });
    toast({
      title: "Success",
      description: h(TransactionHash, {
        hash: response.hash,
        network: network.value,
      }),
    });
  } catch (error) {
    console.error(error);
  }
};
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Sponsor Transaction Flow</CardTitle>
    </CardHeader>
    <CardContent class="flex flex-wrap gap-4">
      <Button @click="onSignTransaction" :disabled="!isSendable">
        Sign as sender
      </Button>
      <Button
        @click="onSignTransactionAsSponsor"
        :disabled="!isSendable || !senderAuthenticator"
      >
        Sign as sponsor
      </Button>
      <Button
        @click="onSignTransaction"
        :disabled="!isSendable || !senderAuthenticator"
      >
        Submit transaction
      </Button>
    </CardContent>
  </Card>
</template>
