// apps/nextjs-example/src/components/transactionFlows/TransactionParameters.tsx
import { cedraClient, isSendableNetwork } from "@/utils";
import {
  InputTransactionData,
  useWallet,
} from "@cedra-labs/wallet-adapter-react";
import { Button } from "../ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { useToast } from "../ui/use-toast";

const CEDRA_COIN = "0x1::cedra_coin::CedraCoin";
const MaxGasAMount = 10000;

export function TransactionParameters() {
  const { toast } = useToast();
  const { connected, account, network, signAndSubmitTransaction, wallet } =
    useWallet();
  let sendable = isSendableNetwork(connected, network?.name);

  const onSignAndSubmitTransaction = async () => {
    if (!account) return;
    const transaction: InputTransactionData = {
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [CEDRA_COIN],
        functionArguments: [account.address, 1], // 1 is in Octas
      },
      options: { maxGasAmount: MaxGasAMount },
    };
    try {
      const commitedTransaction = await signAndSubmitTransaction(transaction);
      const executedTransaction = await cedraClient(network).waitForTransaction(
        {
          transactionHash: commitedTransaction.hash,
        },
      );
      // Check maxGasAmount is respected by the current connected Wallet
      if ((executedTransaction as any).max_gas_amount == MaxGasAMount) {
        toast({
          title: "Success",
          description: `${wallet?.name ?? "Wallet"} transaction ${executedTransaction.hash} executed with a max gas amount of ${MaxGasAMount}`,
        });
      } else {
        toast({
          variant: "destructive",
          title: "Error",
          description: `${wallet?.name ?? "Wallet"} transaction ${executedTransaction.hash} executed with a max gas amount of ${(executedTransaction as any).max_gas_amount}`,
        });
      }
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Validate Transaction Parameters</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-wrap gap-4">
        <Button onClick={onSignAndSubmitTransaction} disabled={!sendable}>
          With MaxGasAmount
        </Button>
      </CardContent>
    </Card>
  );
}

// apps/nuxt-example/components/TransactonFlows/TransactionParameters.vue
<script setup lang="ts">
import { cedraClient, isSendableNetwork } from "@/utils";
import { InputTransactionData } from "@cedra-labs/wallet-adapter-vue";
import { useToast } from "~/components/ui/toast";
const { toast } = useToast();
const { $walletAdapter } = useNuxtApp();
const { network, connected, account, wallet, signAndSubmitTransaction } =
  $walletAdapter || {};

const CEDRA_COIN = "0x1::cedra_coin::CedraCoin";
const MaxGasAMount = 10000;

const isSendable = computed(() =>
  isSendableNetwork(connected.value, network.value?.name || undefined),
);

const onSignAndSubmitTransaction = async () => {
  if (!account) return;
  const transaction: InputTransactionData = {
    data: {
      function: "0x1::coin::transfer",
      typeArguments: [CEDRA_COIN],
      functionArguments: [account.value?.address, 1], // 1 is in Octas
    },
    options: { maxGasAmount: MaxGasAMount },
  };
  try {
    const commitedTransaction = await signAndSubmitTransaction(transaction);
    const executedTransaction = await cedraClient(
      network.value,
    ).waitForTransaction({
      transactionHash: commitedTransaction.hash,
    });
    // Check maxGasAmount is respected by the current connected Wallet
    if ((executedTransaction as any).max_gas_amount == MaxGasAMount) {
      toast({
        title: "Success",
        description: `${wallet.value?.name ?? "Wallet"} transaction ${executedTransaction.hash} executed with a max gas amount of ${MaxGasAMount}`,
      });
    } else {
      toast({
        variant: "destructive",
        title: "Error",
        description: `${wallet.value?.name ?? "Wallet"} transaction ${executedTransaction.hash} executed with a max gas amount of ${(executedTransaction as any).max_gas_amount}`,
      });
    }
  } catch (error) {
    console.error(error);
  }
};
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle> Validate Transaction Parameters </CardTitle>
    </CardHeader>
    <CardContent class="flex flex-wrap gap-4">
      <Button @click="onSignAndSubmitTransaction" :disabled="!isSendable">
        With MaxGasAmount
      </Button>
    </CardContent>
  </Card>
</template>
